"""empty message

Revision ID: a22bc7023298
Revises: 0fe8d49f864f
Create Date: 2024-03-21 18:55:06.040066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22bc7023298'
down_revision = '0fe8d49f864f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_id', sa.Integer(), nullable=False),
    sa.Column('subscribed_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscribed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('subscriber_id', 'subscribed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
